### PR TITLE
fix: expired tg link

### PR DESCRIPTION
**Pull request by zagbc**
Someone in the organization created a new invite link to the "TOL: preparazione test" Telegram group, I guess for bot-related purposes, hopefully without time limits...

### CODE REVIEW

**Comment by EndBug** [comment]
I think the preview deployment is failing because you need to restore the tokens @toto04 @lorenzocorallo

**Review by EndBug — APPROVED** [review]

**Comment by lorenzocorallo** [comment]
> I think the preview deployment is failing because you need to restore the tokens @toto04 @lorenzocorallo

Updated in this repo. Let me know if there are any others related to TOL that need to be updated too.

**Comment by zagbc** [comment]
@EndBug @lorenzocorallo Although constants.ts has been updated, the about page is okay in [dev.](https://polinetworkorg.github.io/preview/PoliNetworkOrg/TheTOLProject/branch/main/#/about) only

**Comment by lorenzocorallo** [comment]
> @EndBug @lorenzocorallo Although constants.ts has been updated, the about page is okay in [dev.](https://polinetworkorg.github.io/preview/PoliNetworkOrg/TheTOLProject/branch/main/#/about) only

That's expected because prod website (online at tol.polinetwork.org) gets updated only on a new version release

**Comment by EndBug** [comment]
Can anyone @PoliNetworkOrg/tol-admins deploy? I don't have my laptop with me

The steps are:
- npm version patch
- commit
- create the corresponding release on GitHub

Then everything should be automated
Do a quick check because I don't remember if the database gets updated automatically

**Pull request merged**
